function plot(constellation, sent, received, nearestSymbol)
    scatter(real(sent), imag(sent), 40,...
                  'MarkerEdgeColor', 'red',...
                  'MarkerFaceColor', 'red',...
                  'LineWidth', 1.5) 
    hold on; 

    scatter(real(received), imag(received), 40,...
                  'MarkerEdgeColor', 'blue',...
                  'MarkerFaceColor', 'blue',...
                  'LineWidth', 1.5)     
    legend('Transmitted', 'Received');
    grid on;          
    hold off;

    figure;
    scatter(real(constellation), imag(constellation), 40,...
                  'MarkerEdgeColor', 'black',...
                  'MarkerFaceColor', 'black',...
                  'LineWidth', 1.5)          
    title('Constellation')
    grid on;  

    figure;
    scatter(real(nearestSymbol), imag(nearestSymbol), 40,...
                  'MarkerEdgeColor', [0.6350 0.0780 0.1840],...
                  'MarkerFaceColor', [0.6350 0.0780 0.1840],...
                  'LineWidth', 1.5)          
    title('Nearest Symbols')
    grid on; 
end

